[tool.poetry]
name = "cars"
version = "0.1.0"
description = ""
authors = ["stephan9971 <tom9876555@yahoo.com.tw>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
