# Generated by Django 5.0.4 on 2024-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=8)),
                ('brand', models.CharField(max_length=20)),
                ('style_body', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
