# Generated by Django 5.0.4 on 2024-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
